version: '3'

services:
  staging:
    image: nginx:1.17.1-alpine
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./local.domain.com.crt:/var/www/html/docker/local.domain.com.crt
        - ./local.domain.com.key:/var/www/html/docker/local.domain.com.key
    ports:
        - 80:80
        - 443:443
    networks:
        - uvod-staging_uvod-net
networks:
    uvod-staging_uvod-net:
        external: true